### ISSUE TITLE
Write article: Automated Deploy using github workflows

### ISSUE THREAD

**Issue by stanleygomes** [stanleygomes/from-tatooine#24]
# automated-deploy
Configuração de um deploy automatizado com Git via SSH, para o Github actions.

A configuração está no arquivo `.github/workflows/deploy.yml` e a trigger é push na master.

```yml
name: Deploy App
# trigger: push na branch master
on:
  push:
    branches:
    - master
jobs:
  build:
    name: Connect
    runs-on: ubuntu-latest
    steps:
    - name: Sign in to remote server and run commands
      uses: appleboy/ssh-action@master
      with:
        # variaveis de ambiente do github secrets
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        script: |
          # entrar na pasta do projeto
          cd ${{ secrets.APP_DIR }}
          # remover mudanças feitas no servidor que não foram comitadas
          # ATENÇÃO:
          # 1. não alterar codigo no servidor, pois será perdido
          # 2. se alguma parte do codigo faz upload de arquivos para dentro da pasta do projeto e essa pasta não está em gitignore, será perdido também
          git checkout -- .
          # baixar o codigo mais atualizado
          git pull ${{ secrets.REMOTE_REF }} master
          # substituir variaveis de ambiente de producao
          cp .env.prd .env
```

Repositorio: `https://github.com/STANLEYGOMES/automated-deploy.git`

Acesso da conta do github:

```env
USERNAME=username
EMAIL=username@gmail.com
PASSWORD=password 
```

# Passo a passo

### 1. Efetuar login via SSH no servidor

```bash
ssh ssh user@host
```

Vai solicitar a senha do ssh:

`PASSWORD=password`

### 2. Acessar a pasta do projeto

```bash
cd /your/app/dir
```

### 3. Inicializar repositorio

```bash
git init
```

### 4. Adicionar uma origem remota

```bash
git remote add origin https://github.com/stanleygomes/automated-deploy.git
```

* Caso queira baixar manualmente via SSH o código atualizado para testar, usar o comando abaixo:

```bash
git pull https://user:password@github.com/stanleygomes/automated-deploy.git master
```

Esse será um dos comandos utilizados pelo CI/CD do github para baixar as atualizações do código.

### 5. Criar as variaveis de ambiente do repositorio

Seguir os passos abaixo na imagem para criar as variaveis de ambiente.

![tutorial](https://i.imgur.com/vfp9R61.png)

Segue abaixo a lista de variaveis que tem que ser criadas. São do tipo chave e valor:

```
HOST=host
USERNAME=username
PASSWORD=password
PORT=22
APP_DIR=/your/app/dir
REMOTE_REF=https://username:password@github.com/stanleygomes/automated-deploy.git
```

REMOTE_REF=https://[USUARIO_GITHUB]:[SENHA_GITHUB]@[REPOSITORIO_GITHUB]

### 6. Efetuar push

Agora, quando for efetuado um push na master, a action criada no github será disparada.

add no .gitignore

```gitignore
uploads
vendor
```

alterar um arquivo, exemplo `index.html`

```html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Teste de deploy automatizado</title>
</head>
<body>

    <h1>Pode mudar esse codigo</h1>
    <h2>E commitar...</h2>
    <h3>E só...</h3>

</body>
</html>
```
